# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QMainWindow,QApplication
import sys
import json
import os
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout, QLabel, QLineEdit, \
    QComboBox, QHBoxLayout, QCheckBox, QFileDialog, QGridLayout, QFileDialog, QMessageBox
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import Qt


class RegisterWindow(QWidget):
    def __init__(self, parent):
        super().__init__()
        self.parent = parent
        self.initUI()

    def initUI(self):
        self.setWindowTitle('注册界面')

        # 设置窗口的初始大小
        self.resize(800, 600)

        # 设置背景图片
        label = QLabel(self)
        # pixmap = QPixmap('./resources/picture_zhuce.png')
        # label.setPixmap(pixmap)
        # label.resize(pixmap.width(), pixmap.height())
        # label.lower()

        # 手机号
        tele_label = QLabel('手机号', self)
        self.tele_edit = QLineEdit(self)
        tele_label.setGeometry(300, 120, 200, 30)
        self.tele_edit.setGeometry(300, 160, 200, 30)

        # 用户名标签和文本框
        username_label = QLabel('用户名', self)
        self.username_edit = QLineEdit(self)
        username_label.setGeometry(300, 200, 200, 30)
        self.username_edit.setGeometry(300, 240, 200, 30)

        # 密码标签和文本框
        password_label = QLabel('密码', self)
        self.password_edit = QLineEdit(self)
        password_label.setGeometry(300, 280, 200, 30)
        self.password_edit.setGeometry(300, 320, 200, 30)

        # 再次密码标签和文本框
        againpassword_label = QLabel('再次输入密码', self)
        self.againpassword_edit = QLineEdit(self)
        againpassword_label.setGeometry(300, 360, 200, 30)
        self.againpassword_edit.setGeometry(300, 400, 200, 30)

        # 确定和取消按钮
        btn_ok = QPushButton('确定', self)
        btn_cancel = QPushButton('回到主界面', self)
        btn_ok.setGeometry(300, 440, 90, 30)
        btn_ok.clicked.connect(self.register)
        btn_cancel.setGeometry(410, 440, 100, 30)
        btn_cancel.clicked.connect(self.show_parent)

    def show_parent(self):
        self.hide()
        self.parent.show()

    def resizeEvent(self, event):
        # 更新背景图片大小
        label = self.findChild(QLabel)
        label.resize(self.size())

    def register(self):
        username = self.username_edit.text()
        password = self.password_edit.text()
        tele = self.tele_edit.text()

        with open('register.txt', 'a') as f:
            f.write(f"{username},{password},{tele}\n")

        print("用户信息已写入register.txt文件")
        self.username_edit.clear()
        self.password_edit.clear()
        self.tele_edit.clear()
        self.againpassword_edit.clear()

